# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mekajira.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mekajira(object):
    def setupUi(self, Mekajira):
        Mekajira.setObjectName("Mekajira")
        Mekajira.setEnabled(True)
        Mekajira.resize(640, 350)
        Mekajira.setMinimumSize(QtCore.QSize(640, 350))
        Mekajira.setMaximumSize(QtCore.QSize(640, 350))
        font = QtGui.QFont()
        font.setFamily("Arial")
        Mekajira.setFont(font)
        self.centralWidget = QtWidgets.QWidget(Mekajira)
        self.centralWidget.setObjectName("centralWidget")
        self.setupFrame = QtWidgets.QFrame(self.centralWidget)
        self.setupFrame.setGeometry(QtCore.QRect(20, 140, 601, 61))
        self.setupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setupFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.setupFrame.setObjectName("setupFrame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.setupFrame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 601, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(22, 11, 22, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.configFileLocation = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.configFileLocation.setInputMask("")
        self.configFileLocation.setText("")
        self.configFileLocation.setReadOnly(False)
        self.configFileLocation.setObjectName("configFileLocation")
        self.horizontalLayout_2.addWidget(self.configFileLocation)
        self.browseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.browseButton.setFlat(False)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_2.addWidget(self.browseButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayoutWidget_2.raise_()
        self.importLabel = QtWidgets.QLabel(self.centralWidget)
        self.importLabel.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.importLabel.setObjectName("importLabel")
        self.epicSelectionFrame = QtWidgets.QFrame(self.centralWidget)
        self.epicSelectionFrame.setGeometry(QtCore.QRect(20, 240, 601, 61))
        self.epicSelectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.epicSelectionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.epicSelectionFrame.setObjectName("epicSelectionFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.epicSelectionFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 601, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(22, 11, 22, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.epicComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.epicComboBox.setEnabled(False)
        self.epicComboBox.setObjectName("epicComboBox")
        self.horizontalLayout.addWidget(self.epicComboBox)
        self.viewInJiraButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.viewInJiraButton.setEnabled(False)
        self.viewInJiraButton.setFlat(False)
        self.viewInJiraButton.setObjectName("viewInJiraButton")
        self.horizontalLayout.addWidget(self.viewInJiraButton)
        self.horizontalLayout.setStretch(0, 1)
        self.epicSelectionLabel = QtWidgets.QLabel(self.centralWidget)
        self.epicSelectionLabel.setGeometry(QtCore.QRect(20, 220, 101, 16))
        self.epicSelectionLabel.setObjectName("epicSelectionLabel")
        self.credentialsFrame = QtWidgets.QFrame(self.centralWidget)
        self.credentialsFrame.setGeometry(QtCore.QRect(20, 40, 601, 61))
        self.credentialsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.credentialsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credentialsFrame.setObjectName("credentialsFrame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.credentialsFrame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(-1, 0, 601, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(22, 11, 22, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.horizontalLayout_3.addWidget(self.usernameLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.passwordLineEdit.setInputMask("")
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setMaxLength(32762)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.horizontalLayout_3.addWidget(self.passwordLineEdit)
        self.submitCredentialsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.submitCredentialsButton.setObjectName("submitCredentialsButton")
        self.horizontalLayout_3.addWidget(self.submitCredentialsButton)
        self.credentialsLabel = QtWidgets.QLabel(self.centralWidget)
        self.credentialsLabel.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.credentialsLabel.setObjectName("credentialsLabel")
        self.createStoriesButton = QtWidgets.QPushButton(self.centralWidget)
        self.createStoriesButton.setGeometry(QtCore.QRect(510, 310, 113, 32))
        self.createStoriesButton.setObjectName("createStoriesButton")
        self.setupFrame.raise_()
        self.importLabel.raise_()
        self.epicSelectionFrame.raise_()
        self.epicSelectionLabel.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.credentialsFrame.raise_()
        self.horizontalLayoutWidget.raise_()
        self.credentialsLabel.raise_()
        self.createStoriesButton.raise_()
        Mekajira.setCentralWidget(self.centralWidget)

        self.retranslateUi(Mekajira)
        QtCore.QMetaObject.connectSlotsByName(Mekajira)

    def retranslateUi(self, Mekajira):
        _translate = QtCore.QCoreApplication.translate
        Mekajira.setWindowTitle(_translate("Mekajira", "Mekajira"))
        self.configFileLocation.setPlaceholderText(_translate("Mekajira", "Enter the location of your configuration file"))
        self.browseButton.setText(_translate("Mekajira", "Browse"))
        self.importLabel.setText(_translate("Mekajira", "Import Settings"))
        self.viewInJiraButton.setText(_translate("Mekajira", "View in Jira"))
        self.epicSelectionLabel.setText(_translate("Mekajira", "Epic Selection"))
        self.usernameLineEdit.setPlaceholderText(_translate("Mekajira", "Username"))
        self.passwordLineEdit.setPlaceholderText(_translate("Mekajira", "Password"))
        self.submitCredentialsButton.setText(_translate("Mekajira", "Create Session"))
        self.credentialsLabel.setText(_translate("Mekajira", "Create Jira Session"))
        self.createStoriesButton.setText(_translate("Mekajira", "Create Stories"))

